baseURL: "https://alguem.de.natal.br/"
defaultContentLanguage: pt-br
languageCode: pt-BR
timeZone: America/Fortaleza
title: "Alguém de Natal, no Brasil"
enableGitInfo: true
menu:
  main:
    - name: "<u>C</u>onteúdo"
      url: /
      weight: 1
    - name: "<u>S</u>obre"
      url: "/sobre"
      weight: 3

permalinks:
  post: /ensina/:title
  term:
    tags: /sobre/:slug
  taxonomy:
    tags: /sobre

params:
  description: "Um repositório de conhecimentos compartilhados com objetividade"

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

module:
  imports:
    - path: github.com/alexandre-mbm/hugo-dead-simple
